require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - examples/**/*

Sorbet/ValidSigil:
  Exclude:
    - ./**/*_pb.rb

Sorbet/FalseSigil:
  Exclude:
    - ./**/*_pb.rb
