# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `twirbet` gem.
# Please instead update this file by running `bin/tapioca gem twirbet`.

# source://twirbet//lib/twirbet/method.rb#4
module Twirbet; end

# source://twirbet//lib/twirbet/errors.rb#216
class Twirbet::AbortedError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#220
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#225
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#146
class Twirbet::AlreadyExistsError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#150
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#155
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#132
class Twirbet::BadRouteError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#136
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#141
  sig { override.returns(::Integer) }
  def status; end
end

# @abstract It cannot be directly instantiated. Subclasses must implement the `abstract` methods below.
#
# source://twirbet//lib/twirbet/errors.rb#9
class Twirbet::BaseError < ::StandardError
  abstract!

  # source://twirbet//lib/twirbet/errors.rb#19
  sig { params(message: ::String, metadata: T::Hash[::String, ::String]).void }
  def initialize(message, metadata = T.unsafe(nil)); end

  # @abstract
  #
  # source://twirbet//lib/twirbet/errors.rb#25
  sig { abstract.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#16
  sig { returns(T::Hash[::String, ::String]) }
  def metadata; end

  # @abstract
  #
  # source://twirbet//lib/twirbet/errors.rb#29
  sig { abstract.returns(::Integer) }
  def status; end

  # source://twirbet//lib/twirbet/errors.rb#43
  sig(:final) { returns(T::Hash[::String, ::String]) }
  def to_hash; end

  # source://twirbet//lib/twirbet/errors.rb#38
  sig(:final) { returns(::String) }
  def to_json; end

  # source://twirbet//lib/twirbet/errors.rb#33
  sig(:final) { returns(::Rack::Response) }
  def to_rack_response; end
end

# source://twirbet//lib/twirbet/errors.rb#48
class Twirbet::CanceledError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#52
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#57
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/client.rb#10
class Twirbet::Client
  include ::Twirbet::DSL
  extend ::Twirbet::DSL::ClassMethods

  # source://twirbet//lib/twirbet/client.rb#24
  sig { params(base_url: ::String, prefix: ::String, transport: ::Twirbet::Transport).void }
  def initialize(base_url, prefix: T.unsafe(nil), transport: T.unsafe(nil)); end

  # source://twirbet//lib/twirbet/client.rb#15
  sig { returns(::String) }
  def base_url; end

  # @raise [ArgumentError]
  #
  # source://twirbet//lib/twirbet/client.rb#31
  sig { params(method_name: ::String, request: T.untyped, headers: T::Hash[::String, ::String]).returns(T.untyped) }
  def call(method_name, request, headers = T.unsafe(nil)); end

  # source://twirbet//lib/twirbet/client.rb#18
  sig { returns(::String) }
  def prefix; end

  # source://twirbet//lib/twirbet/client.rb#21
  sig { returns(::Twirbet::Transport) }
  def transport; end
end

# source://twirbet//lib/twirbet/dsl.rb#7
module Twirbet::DSL
  requires_ancestor { Kernel }

  mixes_in_class_methods ::Twirbet::DSL::ClassMethods

  # source://twirbet//lib/twirbet/dsl.rb#75
  sig { returns(::String) }
  def full_name; end

  # source://twirbet//lib/twirbet/dsl.rb#65
  sig { returns(T.nilable(::String)) }
  def package_name; end

  # source://twirbet//lib/twirbet/dsl.rb#80
  sig { params(name: ::String).returns(T.nilable(::Twirbet::Method)) }
  def rpc(name); end

  # source://twirbet//lib/twirbet/dsl.rb#70
  sig { returns(::String) }
  def service_name; end
end

# source://twirbet//lib/twirbet/dsl.rb#13
module Twirbet::DSL::ClassMethods
  requires_ancestor { Kernel }

  # source://twirbet//lib/twirbet/dsl.rb#42
  sig { returns(::String) }
  def full_name; end

  # source://twirbet//lib/twirbet/dsl.rb#20
  sig { params(name: T.nilable(::String)).void }
  def package(name); end

  # source://twirbet//lib/twirbet/dsl.rb#25
  sig { returns(T.nilable(::String)) }
  def package_name; end

  # source://twirbet//lib/twirbet/dsl.rb#51
  sig { params(name: ::String, request: ::Class, response: ::Class, ruby_method: ::Symbol).void }
  def rpc(name, request, response, ruby_method:); end

  # source://twirbet//lib/twirbet/dsl.rb#57
  sig { returns(T::Hash[::String, ::Twirbet::Method]) }
  def rpcs; end

  # source://twirbet//lib/twirbet/dsl.rb#30
  sig { params(name: ::String).void }
  def service(name); end

  # source://twirbet//lib/twirbet/dsl.rb#35
  sig { returns(::String) }
  def service_name; end
end

# source://twirbet//lib/twirbet/errors.rb#286
class Twirbet::DataLossError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#290
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#295
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#104
class Twirbet::DeadlineExceededError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#108
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#113
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/encoding.rb#5
module Twirbet::Encoding
  class << self
    # source://twirbet//lib/twirbet/encoding.rb#40
    sig { params(object: T.untyped, klass: ::Class, content_type: ::String).returns(T.untyped) }
    def decode(object, klass, content_type); end

    # source://twirbet//lib/twirbet/encoding.rb#20
    sig { params(request: ::Rack::Request).returns(T.untyped) }
    def decode_request(request); end

    # source://twirbet//lib/twirbet/encoding.rb#28
    sig { params(object: T.untyped, content_type: ::String).returns(T.untyped) }
    def encode(object, content_type); end

    # source://twirbet//lib/twirbet/encoding.rb#15
    sig { params(request: T.untyped, klass: ::Class).returns(T.untyped) }
    def encode_request(request, klass); end

    # source://twirbet//lib/twirbet/encoding.rb#10
    sig { params(content_type: T.nilable(::String)).returns(T::Boolean) }
    def supported?(content_type); end
  end
end

# source://twirbet//lib/twirbet/errors.rb#300
module Twirbet::Error
  class << self
    # source://twirbet//lib/twirbet/errors.rb#370
    sig { params(code: ::String, message: ::String).returns(::Twirbet::BaseError) }
    def build(code, message); end

    # source://twirbet//lib/twirbet/errors.rb#349
    sig { params(exception: ::Exception).returns(::Twirbet::BaseError) }
    def from_exception(exception); end

    # source://twirbet//lib/twirbet/errors.rb#365
    sig { params(hash: T::Hash[::String, ::String]).returns(::Twirbet::BaseError) }
    def from_hash(hash); end

    # source://twirbet//lib/twirbet/errors.rb#335
    sig { params(status: ::Integer, reason: ::String, body: ::String).returns(::Twirbet::BaseError) }
    def from_intermidate(status, reason, body); end

    # source://twirbet//lib/twirbet/errors.rb#359
    sig { params(json: ::String).returns(::Twirbet::BaseError) }
    def from_json(json); end

    # source://twirbet//lib/twirbet/errors.rb#328
    sig { params(response: ::Twirbet::Transport::Response).returns(::Twirbet::BaseError) }
    def from_response(response); end
  end
end

# source://twirbet//lib/twirbet/errors.rb#303
Twirbet::Error::CODE_MAP = T.let(T.unsafe(nil), Hash)

# source://twirbet//lib/twirbet/errors.rb#202
class Twirbet::FailedPreconditionError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#206
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#211
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#258
class Twirbet::InternalError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#262
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#267
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#76
class Twirbet::InvalidArgumentError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#80
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#85
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#90
class Twirbet::MalformedError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#94
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#99
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/method.rb#5
class Twirbet::Method
  include ::Comparable

  # source://twirbet//lib/twirbet/method.rb#22
  sig { params(name: ::String, request: ::Class, response: ::Class, ruby_method: ::Symbol).void }
  def initialize(name, request, response, ruby_method:); end

  # source://twirbet//lib/twirbet/method.rb#30
  sig { params(other: T.untyped).returns(::Integer) }
  def <=>(other); end

  # source://twirbet//lib/twirbet/method.rb#10
  sig { returns(::String) }
  def name; end

  # source://twirbet//lib/twirbet/method.rb#13
  sig { returns(::Class) }
  def request; end

  # source://twirbet//lib/twirbet/method.rb#16
  sig { returns(::Class) }
  def response; end

  # source://twirbet//lib/twirbet/method.rb#19
  sig { returns(::Symbol) }
  def ruby_method; end
end

# source://twirbet//lib/twirbet/errors.rb#118
class Twirbet::NotFoundError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#122
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#127
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#230
class Twirbet::OutOfRangeError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#234
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#239
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#160
class Twirbet::PermissionDeniedError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#164
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#169
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#188
class Twirbet::ResourceExhaustedError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#192
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#197
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/service.rb#10
class Twirbet::Service
  include ::Twirbet::DSL
  extend ::Twirbet::DSL::ClassMethods

  # @return [Service] a new instance of Service
  #
  # source://twirbet//lib/twirbet/service.rb#17
  def initialize(handler); end

  # source://twirbet//lib/twirbet/service.rb#22
  sig { params(env: T.untyped).returns(T.untyped) }
  def call(env); end

  # source://twirbet//lib/twirbet/service.rb#15
  sig { returns(T.untyped) }
  def handler; end

  private

  # source://twirbet//lib/twirbet/service.rb#38
  sig { params(method: ::Twirbet::Method, request: ::Rack::Request).returns(T.untyped) }
  def invoke_method(method, request); end

  # @raise [BadRouteError]
  #
  # source://twirbet//lib/twirbet/service.rb#63
  sig { params(request: ::Rack::Request).void }
  def validate_content_type(request); end

  # @raise [BadRouteError]
  #
  # source://twirbet//lib/twirbet/service.rb#56
  sig { params(request: ::Rack::Request).void }
  def validate_method(request); end

  # @raise [BadRouteError]
  #
  # source://twirbet//lib/twirbet/service.rb#70
  sig { params(request: ::Rack::Request).void }
  def validate_path(request); end

  # source://twirbet//lib/twirbet/service.rb#49
  sig { params(request: ::Rack::Request).void }
  def validate_request(request); end
end

# @abstract Subclasses must implement the `abstract` methods below.
#
# source://twirbet//lib/twirbet/transport.rb#5
module Twirbet::Transport
  interface!

  # @abstract
  #
  # source://twirbet//lib/twirbet/transport.rb#52
  sig { abstract.params(request: ::Twirbet::Transport::Request).returns(::Twirbet::Transport::Response) }
  def call(request); end
end

# source://twirbet//lib/twirbet/transport.rb#9
class Twirbet::Transport::Request
  # source://twirbet//lib/twirbet/transport.rb#22
  sig { params(url: ::String, body: ::String, headers: T::Hash[::String, ::String]).void }
  def initialize(url, body, headers); end

  # source://twirbet//lib/twirbet/transport.rb#16
  sig { returns(::String) }
  def body; end

  # source://twirbet//lib/twirbet/transport.rb#19
  sig { returns(T::Hash[::String, ::String]) }
  def headers; end

  # source://twirbet//lib/twirbet/transport.rb#13
  sig { returns(::String) }
  def url; end
end

# source://twirbet//lib/twirbet/transport.rb#29
class Twirbet::Transport::Response
  # source://twirbet//lib/twirbet/transport.rb#42
  sig { params(status: ::Integer, headers: T::Hash[::String, ::String], body: ::String).void }
  def initialize(status, headers, body); end

  # source://twirbet//lib/twirbet/transport.rb#39
  sig { returns(::String) }
  def body; end

  # source://twirbet//lib/twirbet/transport.rb#36
  sig { returns(T::Hash[::String, ::String]) }
  def headers; end

  # source://twirbet//lib/twirbet/transport.rb#33
  sig { returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/transports/net_http_transport.rb#8
module Twirbet::Transports; end

# source://twirbet//lib/twirbet/transports/net_http_transport.rb#9
class Twirbet::Transports::NetHTTPTransport
  include ::Twirbet::Transport

  # source://twirbet//lib/twirbet/transports/net_http_transport.rb#14
  sig { override.params(request: ::Twirbet::Transport::Request).returns(::Twirbet::Transport::Response) }
  def call(request); end
end

# source://twirbet//lib/twirbet/errors.rb#174
class Twirbet::UnauthenticatedError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#178
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#183
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#272
class Twirbet::UnavailableError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#276
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#281
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#244
class Twirbet::UnimplementedError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#248
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#253
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/errors.rb#62
class Twirbet::UnknownError < ::Twirbet::BaseError
  # source://twirbet//lib/twirbet/errors.rb#66
  sig { override.returns(::String) }
  def code; end

  # source://twirbet//lib/twirbet/errors.rb#71
  sig { override.returns(::Integer) }
  def status; end
end

# source://twirbet//lib/twirbet/version.rb#5
Twirbet::VERSION = T.let(T.unsafe(nil), String)
