# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientcompat.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("clientcompat.proto", :syntax => :proto3) do
    add_message "twirp.clientcompat.Empty" do
    end
    add_message "twirp.clientcompat.Req" do
      optional :v, :string, 1
    end
    add_message "twirp.clientcompat.Resp" do
      optional :v, :int32, 1
    end
    add_message "twirp.clientcompat.ClientCompatMessage" do
      optional :service_address, :string, 1
      optional :method_name, :enum, 2, "twirp.clientcompat.ClientCompatMessage.CompatServiceMethod"
      optional :request, :bytes, 3
    end
    add_enum "twirp.clientcompat.ClientCompatMessage.CompatServiceMethod" do
      value :NOOP, 0
      value :METHOD, 1
    end
  end
end

module Twirp
  module Clientcompat
    Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.clientcompat.Empty").msgclass
    Req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.clientcompat.Req").msgclass
    Resp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.clientcompat.Resp").msgclass
    ClientCompatMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.clientcompat.ClientCompatMessage").msgclass
    ClientCompatMessage::CompatServiceMethod = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.clientcompat.ClientCompatMessage.CompatServiceMethod").enummodule
  end
end
